# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5d354f1833d8831eee6b6dcc6870cb08620f511b53f8641d626163efa2bed123d59995581b39128e5ef764afb8e8bc22e82fa5b57673610d216229cccd63383

test:
  secret_key_base: 58bb7ce5b1ecc58c1de57fc9f5e06a72ba36692fcad6f0bcea75a6b699c9ff8118ece198e256163cba90aceb087a4112c639abb3f77ea9173d3ae5e145371a91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
